import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  image: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: null,
  },
  wrapper: {
    width: '85%',
  },
  input: {
    // height: 60,
    flex: 1,
    fontSize: 22,
    fontFamily: 'Gilroy-Regular',
    textAlign: 'center',
    color: '#000000',
  },
  bottomView: {
    // backgroundColor: '#fff',
    opacity: 0.95,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 10,
    paddingBottom: 40,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  loginText: {
    fontSize: 34,
    fontFamily: 'Gilroy-Regular',
    marginTop: 12,
    marginBottom: 4,
    color: 'white',
    textAlign: 'center',
  },
  loginText1: {
    fontSize: 24,
    fontFamily: 'Gilroy-Regular',
    marginTop: 12,
    marginBottom: 4,
    color: 'white',
    textAlign: 'center',
  },
  inputView: {
    // height: 50,
    padding: 0,
    backgroundColor: '#f1f3f6',
    marginTop: 10,
    marginBottom: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  loginButton: {
    backgroundColor: '#454545',
    paddingVertical: 10,
    marginTop: 10,
  },
  loginButtonText: {
    color: '#fff',
    alignSelf: 'center',
    fontSize: 16,
    fontFamily: 'Gilroy-Regular',
  },
});
